
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: apps-franken
    ports:
      - "443:443"
    volumes:
      - ./src/public:/app/public
      - ./src/storage:/app/storage
      - /etc/ssl/letsencrypt:/certs:ro
    working_dir: /app
    restart: unless-stopped
    command: ["/entrypoint.sh"]
